<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class User extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_model');
    } 

    /*
     * Listing of users
     */
    function index()
    {
        $data['users'] = $this->User_model->get_all_users();

        $this->load->view('user/index',$data);
    }

    /*
     * Adding a new user
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nickname' => $this->input->post('nickname'),
				'gender' => $this->input->post('gender'),
				'email' => $this->input->post('email'),
				'comment' => $this->input->post('comment'),
				'cellphone' => $this->input->post('cellphone'),
				'name' => $this->input->post('name'),
            );
            
            $user_id = $this->User_model->add_user($params);
            redirect('user/index');
        }
        else
        {
            $this->load->view('user/add');
        }
    }  

    /*
     * Editing a user
     */
    function edit($user_id)
    {   
        // check if the user exists before trying to edit it
        $user = $this->User_model->get_user($user_id);
        
        if(isset($user['user_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nickname' => $this->input->post('nickname'),
					'gender' => $this->input->post('gender'),
					'email' => $this->input->post('email'),
					'comment' => $this->input->post('comment'),
					'cellphone' => $this->input->post('cellphone'),
					'name' => $this->input->post('name'),
                );

                $this->User_model->update_user($user_id,$params);            
                redirect('user/index');
            }
            else
            {   
                $data['user'] = $this->User_model->get_user($user_id);
    
                $this->load->view('user/edit',$data);
            }
        }
        else
            show_error('The user you are trying to edit does not exist.');
    } 

    /*
     * Deleting user
     */
    function remove($user_id)
    {
        $user = $this->User_model->get_user($user_id);

        // check if the user exists before trying to delete it
        if(isset($user['user_id']))
        {
            $this->User_model->delete_user($user_id);
            redirect('user/index');
        }
        else
            show_error('The user you are trying to delete does not exist.');
    }
    
}
